
### index handler
GET http://127.0.0.1:8080


### update handler
PATCH http://127.0.0.1:8080/
Content-Type: application/json

{
    "age": 20
}

### update handler
PATCH http://127.0.0.1:8080/
Content-Type: application/json

{
    "skills": ["Rust", "TypeScript", "Python"]
}
